name: Building Executable
run-name: ${{ github.actor }} 
on: [push]

permissions:
  contents: write

jobs:
  Run-PS2EXE-on-Windows:
    name: Run PS2EXE on Windows
    runs-on: windows-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v3
        with:
          path: |
            C:\\Modules\\*
            %USERPROFILE%\\Documents\\PowerShell\\Modules\\*
          key: ${{ runner.os }}-SqlServer-PSScriptAnalyzer
      
      - name: Install required PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe
      
      - name: Build binary
        shell: powershell
        run: |
          . ps2exe wg_auto_manager.ps1 wg_auto_manager.exe -NoConsole -noOutput

      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: "v1"
          files: "*.exe"
